theme: jekyll-theme-dinky
title: "Blog | Derek Williams"
description: "Depth articles on data and software engineering with a point of view. I may digress into Agile process, leadership, and other topics.<p><b><a href='https://blog.softwaresalt.com/'>Home</a></b></p><p><img src='https://blog.softwaresalt.com/assets/images/avatar.me.png' width=192 height=200 /></p>"
author: Derek Williams
email: softwaresalt@gmail.com
twitter_username: softwaresalt
github_username:  softwaresalt
linkedin_username: softwaresalt
