theme: jekyll-theme-dinky
title: "Blog | Derek Williams"
description: "Depth articles on data and software engineering with a point of view. I may digress into Agile process, leadership, and philosophical topics.<p><b><a href='https://blog.softwaresalt.com/'>Home</a></b></p>"
author: Derek Williams
email: softwaresalt@gmail.com
twitter_username: softwaresalt
github_username:  softwaresalt
linkedin_username: softwaresalt
